# -*- coding: utf-8 -*-
"""predictive_analysis_gym.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Zgj1_tFCXGbY75eXwFnuyJScd7K1CxY

# Domain Proyek

Optimalisasi aktivitas latihan di pusat kebugaran telah menjadi fokus utama dalam upaya meningkatkan kesehatan masyarakat modern, terutama dalam konteks efektivitas pembakaran kalori. Pemahaman mendalam tentang aktivitas yang menghasilkan pembakaran kalori optimal tidak hanya penting bagi individu yang mengejar tujuan kebugaran pribadi, tetapi juga memiliki implikasi signifikan terhadap kesehatan masyarakat secara keseluruhan. Data dari Organisasi Kesehatan Dunia (WHO, 2020) menunjukkan bahwa tingkat aktivitas fisik yang memadai dapat secara substansial mengurangi risiko berbagai penyakit kronis, namun mayoritas populasi global masih belum mencapai tingkat aktivitas fisik yang direkomendasikan. Tantangan ini semakin diperumit oleh keterbatasan waktu yang dihadapi masyarakat modern, mendorong kebutuhan akan pemahaman yang lebih baik tentang efektivitas berbagai jenis latihan dalam memaksimalkan pembakaran kalori dalam waktu yang tersedia.

Penelitian yang dilakukan oleh Gough et al. (2018) mengungkapkan adanya pergeseran signifikan dalam preferensi masyarakat terhadap program latihan yang lebih efisien namun tetap efektif, mencerminkan kebutuhan akan optimalisasi waktu dalam konteks kesehatan modern. Tren ini memperkuat pentingnya mengidentifikasi dan memahami aktivitas gym yang memberikan manfaat maksimal dalam durasi minimal, memungkinkan individu untuk mencapai tujuan kesehatan mereka meskipun menghadapi kendala waktu. Lebih lanjut, McAuley et al. (2011) menekankan peran krusial faktor psikososial dalam efektivitas latihan, menunjukkan bahwa dukungan sosial dan kepercayaan diri secara signifikan mempengaruhi intensitas dan konsistensi latihan. Temuan ini menggarisbawahi pentingnya mempertimbangkan tidak hanya aspek fisiologis dari pembakaran kalori, tetapi juga konteks psikologis dan sosial yang mempengaruhi efektivitas latihan secara keseluruhan.

Dalam konteks kesehatan masyarakat yang lebih luas, pemahaman tentang efektivitas pembakaran kalori dalam berbagai aktivitas gym memiliki implikasi penting untuk pengembangan strategi intervensi kesehatan yang lebih efektif. Hal ini menjadi semakin relevan mengingat meningkatnya prevalensi penyakit terkait gaya hidup sedenter, seperti obesitas, diabetes, dan penyakit kardiovaskular. Optimalisasi program latihan berdasarkan pemahaman yang lebih baik tentang efektivitas pembakaran kalori dapat membantu mengatasi tantangan kesehatan ini dengan lebih efektif, sambil mempertimbangkan keterbatasan waktu dan sumber daya yang dihadapi masyarakat modern. Dengan demikian, penelitian tentang efektivitas pembakaran kalori dalam aktivitas gym tidak hanya berkontribusi pada pengembangan program kebugaran yang lebih efisien, tetapi juga berperan penting dalam upaya yang lebih luas untuk meningkatkan kesehatan masyarakat dan mengurangi beban penyakit kronis.

Penerapan machine learning memungkinkan identifikasi perilaku gym yang paling efektif, dengan algoritma seperti k-Nearest Neighbors (KNN), Random Forest, dan Boosting. KNN dapat menyarankan latihan berdasarkan karakteristik individu, sementara Random Forest menggabungkan berbagai faktor untuk prediksi pembakaran kalori yang akurat. Boosting meningkatkan ketepatan rekomendasi latihan dengan terus belajar dari kesalahan sebelumnya. Dengan model ini, pusat kebugaran bisa memberikan rekomendasi yang lebih dipersonalisasi, membantu pengguna mencapai tujuan kebugaran secara efisien sekaligus mendukung peningkatan kesehatan masyarakat melalui gaya hidup aktif. Data yang digunakan diambil dari kaggle yang bisa diakses dari link [berikut](https://www.kaggle.com/datasets/valakhorasani/gym-members-exercise-dataset/data)




Dataset ini mencakup profil kebugaran individu, meliputi detail demografis (usia, jenis kelamin), komposisi tubuh (berat badan, tinggi badan, BMI, persentase lemak), metrik detak jantung (Max_BPM, Avg_BPM, Resting_BPM), dan kebiasaan olahraga (Jenis Olahraga, Durasi Sesi, Kalori Terbakar, Frekuensi Olahraga). **BMI** dan **Persentase Lemak** memberikan gambaran tentang komposisi tubuh, dengan **Persentase Lemak** yang biasanya memberikan gambaran yang lebih akurat dibandingkan BMI, terutama untuk individu dengan massa otot yang tinggi. Metrik detak jantung menyoroti kebugaran kardiovaskular, di mana **Resting_BPM** sering kali lebih rendah pada individu yang lebih fit.

Data olahraga menunjukkan intensitas dan preferensi, dengan aktivitas berintensitas tinggi (seperti HIIT atau Kardio) yang cenderung membakar lebih banyak kalori dan memiliki **Avg_BPM** lebih tinggi dibandingkan dengan latihan berintensitas rendah seperti Yoga. **Asupan Air** dan **Tingkat Pengalaman** menambah kedalaman informasi, menunjukkan kebiasaan hidrasi dan tingkat keakraban dengan kebugaran, yang dapat memengaruhi hasil latihan dan detak jantung saat istirahat. Dataset ini memungkinkan pemahaman yang luas tentang tingkat kebugaran individu dan memberikan wawasan yang berguna untuk personalisasi rencana kebugaran dan kesehatan.

# Business Understanding

## Problem Statement

1. Bagaimana cara meningkatkan efektifitas jumlah Kalori Terbakar pada Latihan?
2. Bagaimana cara optimalkan latihan, jika ingin mencapai target Kadar Lemak Tubuh tertentu?
3. Apakah ada perbedaan antara Laki-laki dan Perempuan dalam preferensi latihan?
4. Apakah Tingkat Kemahiran mempengaruhi preferensi latihan?

## Goals

1. Membuat model yang memprediksi Kalori Terbakar dalam Latihan.
2. Membuat model yang memprediksi Kadar Lemak Tubuh.
3. Mencari perbedaan preferensi Laki-laki dan Perempuan.
4. Mencari preferensi setiap tingkat Kemahiran.

## Solution

1. Menggunakan 4 Algoritma Machine Learning untuk membuat model yang memprediksi Kalori Terbakar dan Kadar Lemak Tubuh.
2. Menggunakan Exploratory Data Analysis (EDA) untuk menentukan pengaruh Jenis Kelamin dan Tingkat Kemahiran dalam preferensi Latihan.

# Mengimpor Library

Semua *Library* diimpor terlebih dahulu untuk digunakan pada tahap selanjutnya.
"""

import textwrap
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import xgboost as xgb

from xgboost import XGBClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV, train_test_split
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder, OneHotEncoder, StandardScaler
from sklearn.metrics import (
    ConfusionMatrixDisplay,
    accuracy_score,
    classification_report,
    mean_absolute_error,
    mean_squared_error,
    r2_score,
    explained_variance_score
)

from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor
import kagglehub
import shutil

"""# **Pemahaman Data**

## Pemuatan Data

Data diambil dari kaggle pada tautan berikut "valakhorasani/gym-members-exercise-dataset" dan diunduh ke dalam root sistem Google Colab.
"""

path = kagglehub.dataset_download("valakhorasani/gym-members-exercise-dataset")
print("Path to dataset files:" , path)

"""Data dipindahkan ke dalam drive agar dapat memudahkan penggunaan di Google Colab."""

source_path = '/root/.cache/kagglehub/datasets/valakhorasani/gym-members-exercise-dataset/versions/1/gym_members_exercise_tracking.csv'
destination_path = '/content/drive/MyDrive/Predictive/'
shutil.copy(source_path, destination_path)

"""Data dibuka melalui dataframe dan ditampilkan sekilas menggunakan fungsi .head() dan .shape"""

data = pd.read_csv("/content/drive/MyDrive/Predictive/gym_members_exercise_tracking.csv")
# Menampilkan ukuran data
print(data.shape)
# Melihat 5 baris pertama data
data.head()

"""Tampilan diatas menunjukkan ada 973 rekod data dengan 15 jenis informasi yang dapat dianalisis.

## Analisis Data Eksploratif (*EDA*)

### Deskripsi Variabel

#### Arti Variabel

Berikut ini adalah arti dari setiap variabel yang akan digunakan.

| Variabel                           | Keterangan |
|-------------------------------------|-------------------|
| Age                                  | Umur dari pengunjung pusat kebugaran dalam Tahun|
| Gender                               |Jenis kelamin dari pengunjung pusat kebugaran (Pria, Wanita) |
| Weight (kg)                          | Berat badan pengunjung pusat kebugaran dalam Kilogram |
| Height (m)                           |Tinggi pengunjung pusat kebugaran dalam Centimeter|
| Max_BPM                              | Laju maksimal detak jantung permenit peserta|
| Avg_BPM                              |Laju rata-rata detak jantung permenit peserta  |
| Resting_BPM                          | Laju detak jantung istirahat permenit peserta|
| Session_Duration (hours)            | Durasi penggunaan pusat kebugaran dalam Jam|
| Calories_Burned                      | Jumlah kalori yang terbakar dalam Kal|
| Workout_Type                         | Jenis Latihan yang dilakukan pelanggan (HIIT, Strength, Cardio, Yoga)|
| Fat_Percentage                       | Kadar lemak tubuh dari pengunjung dalam persen (%) |
| Water_Intake (liters)               | Jumlah air yang diminum selama latihan dalam Liter |
| Workout_Frequency (days/week)       | Frekuensi kunjungan ke pusat kebugaran dalam seminggu |
| Experience_Level                     | Tingkat kemahiran dalam melakukan latihan dalam tiga tingkatan (1, 2, 3) |
| BMI                                  | Indeks massa tubuh dari pengunjung pusat kebugaran                 |

Beberapa variabel merupakan variabel kategorik, dan sisanya adalah variabel numerik. Penjelasan lebih lanjut mengenai nilai variabel sebagai berikut.

Variabel `Workout_Type` yang berarti Jenis Latihan memiliki penjelasan nilai variabel seperti berikut

| Variabel                           | Keterangan |
|-------------------------------------|-------------------|
| HIIT| *High-Intensity Interval Training* yaitu latihan intensitas tinggi yang dilakukan dengan durasi cepat disertai istirahat dan pergantian gerakan|
| Strength| Olahraga latihan untuk meningkatkan kekuatan fisik seperti angkat beban atau *bench-press* |
| Yoga| Olahraga yang menggabungkan gerakan, pernapasan, dan meditasi untuk meningkatkan kesehatan fisik dan keseimbangan mental.|
|Cardio|Olahraga yang meningkatkan laju detak jantung dan laju nafas dengan berbagai intensitas seperti bersepeda, lari, olahraga *treadmill*|

#### Tipe Variabel
"""

data.info()

"""Ditemukan ada enam variabel bertipe int64, dua variabel bertipe object dan tujuh variabel bertipe float64. Selanjutnya dapat dilihat bahwa seluruh data bertipe float64 adalah variabel numerik dan seluruh data bertipe object adalah variabel kategorik. Sedangkan data bertipe int64, dua diantaranya bisa digunakan sebagai variabel kategorik dan empat diantaranya adalah variabel numerik.

#### Deskripsi statistik dari data
"""

data.describe()

"""Informasi statistik tersebut menunjukkan simpangan baku yang cukup tinggi yang menandakan perbedaan profil yang cukup signifikan antar responden. Beragam profil dalam data bisa berarti adanya berbagai demografi yang tercangkup dari data tersebut yang dapat dianalisis.

#### Pembersihan Data
"""

pd.DataFrame({'Nilai yang Kosong':data.isnull().sum()})

"""Tidak ditemukan adanya data yang kosong."""

data.duplicated().sum()

"""Tidak ditemukan adanya data ganda.

#### Pencilan

*Boxplot* digunakan untuk melihat penyebaran data.
"""

kolom=["Age",
       "Weight (kg)",
       "Height (m)",
       "Max_BPM",
       "Avg_BPM",
       "Resting_BPM",
       "Session_Duration (hours)",
       "Calories_Burned",
       "Fat_Percentage",
       "Water_Intake (liters)",
       "Workout_Frequency (days/week)",
       "Experience_Level",
       "BMI"]

# Membentuk plot berukuran 24 x 12
plt.figure(figsize = (24, 12))

# Membentuk plot berisi 8 subplot, dengan setiap subplot merupakan boxplot
for i in range(len(kolom)):

    # Membentuk plot dengan subplot berukuran 4 x 2
    plt.subplot(7, 2, i + 1)
    sns.boxplot(x = data[kolom[i]])
    plt.title('Boxplot dari {}'.format(kolom[i]))
    plt.tight_layout()

"""Tampilan diatas menunjukkan tiga kolom informasi yang mempunyai nilai datum diluar batas kuartil. Kolom berat badan dan BMI mempunyai beberapa potensi pencilan yaitu beberapa datum yang berada diatas nilai kuartil atas. Namun data ini masih terbilang wajar mengingat pusat kebugaran merupakan tempat yang mengakomodasi program penurunan berat badan jadi memiliki berat badan tinggi bukan merupakan anomali. Data kalori terbakar juga memiliki beberapa datum yang berada diluar kuartil atas. Ini bukan merupakan pencilan yang harus dihilangkan karena sangat memungkinkan untuk seseorang mahir dalam latihan kebugaran sehingga dapat membakar kalori lebih banyak dalam satu waktu.

#### Koreksi tipe data

Dua kolom informasi bertipe int64 dapat diperlakukan sebagai data kategorik. Oleh karena itu dibuatlah kolom baru mengunakan data tersebut dengan mengubah jenis data menjadi string. Selanjutnya string tersebut diubah menjadi tipe data object agar bisa dikenali filter tipe object seperti data kategorik lainnya.
"""

# Membuat kolom baru sebagai kategori bukan numerik
data['Workout_Frequency_cat'] = data['Workout_Frequency (days/week)'].astype("str")
data['Experience_Level_cat'] = data['Experience_Level'].astype("str")

# Menjadikan tipe data sebagai object agar bisa dikelompokkan sebagai kategorik
data['Workout_Frequency_cat'] = data['Workout_Frequency_cat'].astype("object")
data['Experience_Level_cat'] = data['Experience_Level_cat'].astype("object")

"""### Analisis Univariat"""

# Membentuk list berisi kolom-kolom numerik
kolom_numerik = ['Age',
                 'Weight (kg)',
                 'Height (m)',
                 'Max_BPM',
                 'Avg_BPM',
                 'Resting_BPM',
                 'Session_Duration (hours)',
                 'Calories_Burned',
                 'Fat_Percentage',
                 'Water_Intake (liters)',
                 'Workout_Frequency (days/week)',
                 'Experience_Level',
                 'BMI']

# Membentuk list berisi kolom-kolom kategorik
kolom_kategorik = ['Gender', 'Workout_Type', 'Workout_Frequency_cat', 'Experience_Level_cat']

# Menampilkan list kolom numerik dan kolom kategorik
print("Kolom-kolom numerik: ", kolom_numerik)
print("Kolom-kolom kategorik: ", kolom_kategorik)

# Menghitung jumlah nilai yang unik/berbeda dari masing-masing variabel pada kolom kategorik
jumlah_unik = data[kolom_kategorik].nunique()

# Menampilkan nilai yang unik/berbeda dari masing-masing variabel pada kolom kategorik
nilai_unik = data[kolom_kategorik].apply(lambda x: x.unique())

# Menampilkan hasil dalam bentuk DataFrame
pd.DataFrame({"Total Nilai Berbeda": jumlah_unik, "Nilai-Nilai": nilai_unik})

"""Ada 4 variabel kategorik yang bisa digunakan untuk mengelompokkan data."""

tipe_olahraga = data.Workout_Type.value_counts()
tipe_olahraga

# Membuat variabel label dan size
label = tipe_olahraga.index.tolist()
size = tipe_olahraga.values.tolist()

# Membentuk pie chart untuk melihat penyebaran data dari masing-masing tingkat berat badan
plt.figure(figsize = (8, 8))
plt.pie(size, labels = label, autopct = "%1.1f%%", startangle = 120, radius = 0.75)

# Menambahkan legend pada pie chart
plt.legend(loc = "upper left", bbox_to_anchor = (1, 1))

# Menambahkan judul pada plot
plt.title("Distribusi Tipe Olahraga")

# Menampilkan plot
plt.show()

"""Distribusi jumlah pelanggan sesuai jenis latihan yang dilakukan cukup tersebar merata dengan latihan Strength sebagai latihan yang paling banyak dilakukan meskipun tidak jauh berbeda dengan jenis latihan lainnya."""

data['Workout_Frequency_cat'] = data['Workout_Frequency_cat'].astype('category')
data['Experience_Level_cat'] = data['Experience_Level_cat'].astype('category')

# Membentuk plot dengan subplot sejumlah 4 berukuran 2 x 2
fig, axes = plt.subplots(2, 2, figsize=(9, 9))
axes = axes.flatten()

# Mendeskripsikan kolom-kolom kategorik yang akan digunakan
kolom_kategorik = ["Gender", "Workout_Type", "Workout_Frequency_cat", "Experience_Level_cat"]
deskripsi_kolom_kategorik = ["Jenis Kelamin", "Jenis Latihan", "Frekuensi Latihan", "Tingkat Kemahiran"]

# Membentuk plot jumlah dalam bentuk bar plot untuk masing-masing kolom
for i, kolom in enumerate(kolom_kategorik):
    sns.countplot(x=kolom, data=data, ax=axes[i], hue=kolom)

    # Menambahkan judul untuk masing-masing plot
    judul = "\n".join(textwrap.wrap(f"Plot Jumlah dari {deskripsi_kolom_kategorik[i]}", width=40))
    axes[i].set_title(judul, size=12)

    # Mengatur label
    axes[i].tick_params(axis="x", labelrotation=0)
    axes[i].tick_params(axis="both", which="major", labelsize=12)
    axes[i].set_xlabel("")
    axes[i].set_ylabel("Jumlah")

# Mengatur susunan agar tidak berhimpitan
plt.tight_layout()

# Menampilkan plot
plt.show()

"""Pengunjung pusat kebugaran lebih banyak laki-laki meskipun bedanya tidak banyak dengan pengunjung perempuan. Pengunjung yang paling banyak datang ke pusat kebugaran adalah yang datang dua kali seminggu. Jumlah anggota variabel `Tingkat Kemahiran` cukup timpang dengan `Tingkat Kemahiran` 3 mempunyai anggota paling sedikit dibanding yang lain."""

# Membentuk plot dengan subplot sejumlah 8 berukuran 15 x 8
fig, axes = plt.subplots(3, 5, figsize = (15, 9))

# Mengubah array multi dimensi menjadi array 1 dimensi
axes = axes.flatten()

# Menambahkan satuan dari masing-masing kolom
labels = ["Tahun","Kilogram", "Meter", "", "", "", "Jam", "Kalori", "Persen", "Liter", "","","Index"]

# Mendeskripsikan kolom-kolom numerik yang akan digunakan
deskripsi_kolom_numerik =  ['Usia',
                            'Berat Badan',
                            'Tinggi Badan',
                            'Max_BPM',
                            'Avg_BPM',
                            'Resting_BPM',
                            'Durasi Latihan',
                            'Kalori Terbakar',
                            'Kadar Lemak Tubuh',
                            'Asupan Air',
                            'Frekuensi Latihan',
                            'Tingkat Kemahiran',
                            'BMI']

# Membentuk plot jumlah dalam bentuk histogram plot untuk masing-masing kolom
for i, kolom in enumerate(data[kolom_numerik].columns):
    sns.histplot(data = data, x = kolom, kde = True, ax = axes[i])

    # Menambahkan judul untuk masing-masing plot
    judul = "\n".join(textwrap.wrap(f"Plot Histogram dari {deskripsi_kolom_numerik[i]}", width = 30))
    axes[i].set_title(judul)
    axes[i].title.set_size(12)

    # Mengatur label x
    axes[i].set_xlabel(labels[i])
    axes[i].set_ylabel("Total")

# Mengatur susunan agar tidak berhimpitan
plt.tight_layout()

# Menampilkan plot
plt.show()

"""Variabel `Durasi Latihan` dan `Kalori Terbakar` memiliki data yang terdistribusi cukup normal. Variabel `Berat Badan`,`Tinggi Badan`, dan `BMI` memiliki distribusi yang miring ke kanan yang berarti kebanyakan anggotanya berada di bawah rata-rata. Sedangkan variabel `Kadar Lemak Tubuh` dan `Asupan Air` memiliki distribusi yang miring ke kiri yaitu anggotanya lebih banyak yang memiliki nilai diatas rata-rata. Lalu sisanya yaitu `Usia`, `Max BPM`, `Resting BPM`, `Avg BPM`, `Frekuensi Latihan` dan `Tingkat Kemahiran` tidak berdistribusi normal.

### Analisis Multivariat

#### 1. Analisis Berbagai Distribusi Kategori Berdasarkan Jenis Kelamin
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Mengatur ukuran keseluruhan untuk semua subplots
fig, axes = plt.subplots(3, 2, figsize=(8, 12))  # 4 rows, 2 columns (laki-laki dan perempuan)
fig.suptitle("Analisis Berbagai Distribusi Kategori Berdasarkan Jenis Kelamin")

# Membuat subset data untuk setiap jenis kelamin
data_male = data.query("Gender == 'Male'")
data_female = data.query("Gender == 'Female'")

# Subplot untuk Workout Type
order = sorted(data['Workout_Type'].unique())
sns.countplot(x="Workout_Type", data=data_male, ax=axes[0, 0], color="#1f77b4", order=order)
axes[0, 0].set_title("Tipe Latihan untuk Laki-laki")
axes[0, 0].set_xlabel("Jenis Latihan")
axes[0, 0].set_ylabel("Jumlah")
axes[0, 0].tick_params(axis='x', rotation=45)

sns.countplot(x="Workout_Type", data=data_female, ax=axes[0, 1], color="#ff7f0e", order=order)
axes[0, 1].set_title("Tipe Latihan untuk Perempuan")
axes[0, 1].set_xlabel("Jenis Latihan")
axes[0, 1].set_ylabel("Jumlah")
axes[0, 1].tick_params(axis='x', rotation=45)

# Subplot untuk Workout Frequency
sns.countplot(x="Workout_Frequency_cat", data=data_male, ax=axes[1, 0], color="#1f77b4")
axes[1, 0].set_title("Frekuensi Latihan untuk Laki-laki")
axes[1, 0].set_xlabel("Frekuensi per minggu")
axes[1, 0].set_ylabel("Jumlah")
axes[1, 0].tick_params(axis='x')

sns.countplot(x="Workout_Frequency_cat", data=data_female, ax=axes[1, 1], color="#ff7f0e")
axes[1, 1].set_title("Frekuensi Latihan untuk Perempuan")
axes[1, 1].set_xlabel("Frekuensi per minggu")
axes[1, 1].set_ylabel("Jumlah")
axes[1, 1].tick_params(axis='x')

# Subplot untuk Tingkat Kemahiran
sns.countplot(x="Experience_Level_cat", data=data_male, ax=axes[2, 0], color="#1f77b4")
axes[2, 0].set_title("Tingkat Kemahiran untuk Laki-laki")
axes[2, 0].set_xlabel("Tingkat Kemahiran")
axes[2, 0].set_ylabel("Jumlah")
axes[2, 0].tick_params(axis='x')

sns.countplot(x="Experience_Level_cat", data=data_female, ax=axes[2, 1], color="#ff7f0e")
axes[2, 1].set_title("Tingkat Kemahiran untuk Perempuan")
axes[2, 1].set_xlabel("Tingkat Kemahiran")
axes[2, 1].set_ylabel("Jumlah")
axes[2, 1].tick_params(axis='x')

# Mengatur layout agar tidak tumpang tindih
plt.tight_layout(rect=[0, 0, 1, 0.96])
plt.show()

"""Distribusi penyebaran data antara laki-laki dan perempuan memiliki penyebaran yang hampir sama pada setiap kategori. Perbedaan hanya terlihat pada kategori `Jenis Latihan` yaitu perempuan lebih terdistribusi ke `Kardio` sedangkan laki-laki surplus distribusi pada jenis latihan `Yoga`.

#### 2. Distribusi Jenis Latihan Berdasarkan Level Kemahiran
"""

# Group by Experience_Level and Workout_Type, then get counts
workout_counts = data.groupby(['Experience_Level', 'Workout_Type'], observed=False).size().unstack(fill_value=0)

# Normalize to get percentages
workout_percentages = workout_counts.divide(workout_counts.sum(axis=1), axis=0) * 100

# Create a figure with two subplots (side by side)
fig, axes = plt.subplots(1, 2, figsize=(14, 6))  # 1 row, 2 columns

# Plot the bar chart with counts on the first subplot
workout_counts.plot(kind='bar', stacked=True, ax=axes[0], figsize=(12, 6))
axes[0].set_title("Distribusi Jenis Latihan Berdasarkan Tingkat Kemahiran")
axes[0].set_xlabel("Tingkat Kemahiran")
axes[0].set_ylabel("Jumlah")
axes[0].tick_params(axis='x', rotation=0)
axes[0].legend(title='Jenis Latihan', bbox_to_anchor=(1.05, 1), loc='upper left')

# Plot the bar chart with percentages on the second subplot
workout_percentages.plot(kind='bar', stacked=True, ax=axes[1], figsize=(12, 6))
axes[1].set_title("Distribusi Jenis Latihan Berdasarkan Tingkat Kemahiran (%)")
axes[1].set_xlabel("Tingkat Kemahiran")
axes[1].set_ylabel("Persentase (%)")
axes[1].tick_params(axis='x', rotation=0)
axes[1].legend(title='Jenis Latihan', bbox_to_anchor=(1.05, 1), loc='upper left')

# Adjust layout to avoid overlap
plt.tight_layout()

# Show the plots
plt.show()

"""`Tingkat Kemahiran` tidak memengaruhi preferensi jenis latihan yang dilakukan karena secara persentase distribusinya serupa. Namun terlihat dari jumlah total `Tingkat Kemahiran` 1 dan 2 mayoritas melakukan latihan `Strength` sedangkan pada `Tingkat Kemahiran` 3 lebih banyak yang melakukan `Yoga`.

#### 3. Distribusi Nilai Kadar Lemak Tubuh dari berbagai Kategori
"""

# Create a figure with three subplots (side by side)
fig, axes = plt.subplots(1, 3, figsize=(18, 6))  # 1 row, 3 columns

# Strip plot of fat percentage against Experience_Level on the first subplot
sns.stripplot(y="Experience_Level_cat",
              x="Fat_Percentage",
              data=data,
              ax=axes[0])

axes[0].set_title("Distribusi Nilai Kadar Lemak Tubuh dari Tingkat Kemahiran")
axes[0].set_xlabel("Kadar Lemak Tubuh (%)")
axes[0].set_ylabel("Tingkat Kemahiran")

# Strip plot of fat percentage against Workout Frequency on the second subplot
sns.stripplot(y="Workout_Frequency_cat",
              x="Fat_Percentage",
              data=data,
              ax=axes[1])

axes[1].set_title("Distribusi Nilai Kadar Lemak Tubuh dari Frekuensi latihan")
axes[1].set_xlabel("Kadar Lemak Tubuh (%)")
axes[1].set_ylabel("Frekuensi Latihan")

# Strip plot of fat percentage against Workout Type on the third subplot
sns.stripplot(y="Workout_Type",
              x="Fat_Percentage",
              data=data,
              ax=axes[2])

axes[2].set_title("Distribusi Nilai Kadar Lemak Tubuh dari Jenis Latihan")
axes[2].set_xlabel("Kadar Lemak Tubuh (%)")
axes[2].set_ylabel("Jenis Latihan")



# Adjust layout to avoid overlap
plt.tight_layout()

# Show the plot
plt.show()

"""`Tingkat Kemahiran` 3 mempunyai `Kadar Lemak Tubuh` antara 10-15% sedangkan Tingkat Kemahiran 1 dan 2 antara 20-35%. `Kadar Lemak Tubuh` yang relatif tinggi ditemukan pada pengunjung yang datang dua sampai tiga kali seminggu yaitu antara 20-35%. Pengunjung yang datang lima kali dalam seminggu mempunyai rentang `Kadar Lemak Tubuh` relatif rendah antar 10-20% sedangkan pada kelompok pengunjung yang datang empat kali dalam seminggu tersebar antara 10-35% `Kadar Lemak Tubuh`.

#### 4. Distribusi Kalori Terbakar dari berbagai Kategori
"""

import seaborn as sns
import matplotlib.pyplot as plt

# Create a figure with three subplots (side by side)
fig, axes = plt.subplots(1, 3, figsize=(18, 6))  # 1 row, 3 columns

# Strip plot of fat percentage against Experience_Level on the first subplot
sns.stripplot(y="Experience_Level_cat",
              x="Calories_Burned",
              data=data,
              ax=axes[0],
              # jitter=True,  # Uncomment if you want to add jitter to the points
              # dodge=False,
              # hue="Experience_Level",  # Uncomment for color coding by experience level
              # palette="Set2",  # Optional palette
              # alpha=0.6
              )

axes[0].set_title("Distribusi Nilai Kalori Terbakar dari Tingkat Kemahiran")
axes[0].set_xlabel("Kalori Terbakar")
axes[0].set_ylabel("Tingkat Kemahiran")

# Strip plot of fat percentage against Workout Frequency on the second subplot
sns.stripplot(y="Workout_Frequency_cat",
              x="Calories_Burned",
              data=data,
              ax=axes[1],
              # jitter=True,  # Uncomment if you want to add jitter to the points
              # dodge=False,
              # hue="Experience_Level",  # Optional: add hue if you want different colors for Experience Level
              # palette="Set2",  # Optional: specify palette for different hues
              # alpha=0.6
              )

axes[1].set_title("Distribusi Nilai Kalori Terbakar dari Frekuensi Latihan")
axes[1].set_xlabel("Kalori Terbakar")
axes[1].set_ylabel("Frekuensi Latihan")

# Strip plot of fat percentage against Workout Type on the third subplot
sns.stripplot(y="Workout_Type",
              x="Calories_Burned",
              data=data,
              ax=axes[2],
              # jitter=True,  # Uncomment if you want to add jitter to the points
              # dodge=False,
              # hue="Experience_Level",  # Optional: add hue if you want different colors for Experience Level
              # palette="Set2",  # Optional: specify palette for different hues
              # alpha=0.6
              )

axes[2].set_title("Distribusi Nilai Kalori Terbakar dari Jenis Latihan")
axes[2].set_xlabel("Kalori Terbakar")
axes[2].set_ylabel("Jenis Latihan")



# Adjust layout to avoid overlap
plt.tight_layout()

# Show the plot
plt.show()

"""Tingkat Kemahiran 1 memiliki sebaran luas, 400-1300 kalori terbakar per latihan. Tingkat Kemahiran 2 lebih terfokus, 600-1400 kalori. Tingkat Kemahiran 3 memiliki sebaran jarang dengan rentang tinggi, 900-1800 kalori.
Orang yang datang 2-3 kali seminggu memiliki sebaran 400-1400 kalori terbakar per latihan. Pengunjung dengan kehadiran 4 kali seminggu lebih tersebar, 600-1800 kalori. Pengunjung yang datang 5 kali seminggu memiliki nilai rentang tinggi, 900-1800 kalori.

#### 5. Distribusi Indeks Massa Tubuh dari berbagai Kategori
"""

# Create a figure with three subplots (side by side)
fig, axes = plt.subplots(1, 3, figsize=(18, 6))  # 1 row, 3 columns

# Strip plot of fat percentage against Experience_Level on the first subplot
sns.stripplot(y="Experience_Level_cat",
              x="BMI",
              data=data,
              ax=axes[0])

axes[0].set_title("Distribusi Nilai Indeks Masa Tubuh dari Tingkat Kemahiran")
axes[0].set_xlabel("Indeks Massa Tubuh")
axes[0].set_ylabel("Tingkat Kemahiran")

# Strip plot of fat percentage against Workout Frequency on the second subplot
sns.stripplot(y="Workout_Frequency_cat",
              x="BMI",
              data=data,
              ax=axes[1])

axes[1].set_title("Distribusi Nilai Indeks Masa Tubuh dari Frekuensi latihan")
axes[1].set_xlabel("Indeks Massa Tubuh")
axes[1].set_ylabel("Frekuensi Latihan")

# Strip plot of fat percentage against Workout Type on the third subplot
sns.stripplot(y="Workout_Type",
              x="BMI",
              data=data,
              ax=axes[2])

axes[2].set_title("Distribusi Nilai Indeks Masa Tubuhh dari Jenis Latihan")
axes[2].set_xlabel("Indeks Massa Tubuh")
axes[2].set_ylabel("Jenis Latihan")



# Adjust layout to avoid overlap
plt.tight_layout()

# Show the plot
plt.show()

"""Tingkat kemahiran 1, nilai IMT tersebar luas dari sekitar 15 hingga 50. Pada tingkat kemahiran 2, distribusi menjadi lebih sempit dengan lebih sedikit pencilan pada IMT yang tinggi. Sementara itu, pada tingkat kemahiran 3, nilai IMT lebih terkonsentrasi dalam rentang 25-35.

Peserta yang berlatih 2-3 kali seminggu memiliki nilai IMT yang tersebar luas, termasuk beberapa pencilan dengan IMT di atas 40. Namun, ketika frekuensi latihan meningkat menjadi 4-5 kali seminggu, distribusi IMT lebih terkonsentrasi pada rentang 20-35.

Peserta Yoga dan HIIT memiliki distribusi IMT yang cukup luas, termasuk beberapa dengan IMT di atas 40. Sebaliknya, peserta yang memilih latihan Kardio dan Latihan Kekuatan cenderung lebih terkonsentrasi dalam rentang IMT 25-35.

#### 6. *Heat Map*
"""

# Mencari korelasi antara masing-masing variabel numerik dengan korelasi pearson
corr = data.corr(method = "pearson", numeric_only = True)

# Membentuk heatmap antara masing-masing variabel numerik dan ditampilkan dalam bentuk desimal 2 angka di belakang koma
plt.figure(figsize = (8, 6))
sns.heatmap(corr, annot = True, fmt = ".2f", annot_kws = {"size": 10})

# Menambahkan judul pada plot
plt.title("Heatmap dari Korelasi Antara Masing-Masing Variabel Numerik")

# Menampilkan plot
plt.show()

"""Berdasarkan heatmap korelasi, BMI memiliki korelasi positif yang sangat kuat dengan berat badan (0.85), karena memang merupakan faktor utama dalam perhitungan BMI. Frekuensi latihan berhubungan positif dengan durasi sesi latihan (0.64) dan pembakaran kalori (0.36), yang juga mencerminkan bahwa tingkat kemahiran meningkat seiring dengan lebih banyaknya frekuensi dan durasi latihan (korelasi dengan tingkat kemahiran adalah 0.69 dan 0.76). Selain itu, asupan air memiliki hubungan positif dengan frekuensi latihan (0.44) dan durasi latihan (0.28), menunjukkan bahwa peserta yang lebih aktif cenderung mengonsumsi lebih banyak air. Di sisi lain, persentase lemak tubuh memiliki korelasi negatif dengan pembakaran kalori (-0.60) dan frekuensi latihan (-0.54), mengindikasikan bahwa aktivitas fisik yang lebih sering dan pembakaran kalori yang lebih tinggi cenderung berhubungan dengan lemak tubuh yang lebih rendah. Secara keseluruhan, aktivitas fisik yang teratur dan intens berkontribusi pada tingkat kebugaran yang lebih baik, asupan air yang lebih tinggi, dan lemak tubuh yang lebih rendah.

#### 7. *Pair Plot*
"""

# Mengamati hubungan antar fitur numerik dengan fungsi pairplot()
sns.pairplot(data, diag_kind = 'kde')

"""Berdasarkan pairplot, variabel numerik seperti berat badan, tinggi badan, dan durasi sesi latihan menunjukkan distribusi yang mendekati normal, sementara variabel seperti frekuensi latihan dan tingkat kemahiran bersifat kategorikal. Hubungan positif yang kuat terlihat antara BMI dan berat badan, serta antara kalori terbakar dan durasi sesi latihan, menunjukkan bahwa berat badan memengaruhi BMI dan durasi sesi yang lebih lama menghasilkan pembakaran kalori yang lebih banyak. Selain itu, asupan air cenderung meningkat seiring dengan frekuensi latihan yang lebih tinggi. Di sisi lain, variabel seperti detak jantung (Max_BPM dan Resting_BPM) tidak menunjukkan hubungan yang jelas dengan variabel lain. Beberapa pencilan teridentifikasi pada variabel seperti BMI dan kalori terbakar, yang dapat mencerminkan pola unik pada peserta tertentu. Secara keseluruhan, pairplot ini menunjukkan beberapa hubungan signifikan antarvariabel, meskipun beberapa variabel lain memiliki korelasi yang lemah atau tidak jelas, mencerminkan keragaman data peserta.

#### 8. Perbandingan Kalori Terbakar dengan Kadar Lemak Tubuh
"""

# Membentuk plot jumlah dalam bentuk bar plot antara tingkat berat badan dengan jenis kelamin
plt.figure(figsize = (8, 6))
sns.regplot(x = "Fat_Percentage", data = data, y = "Calories_Burned")

# Menambahkan judul pada plot
plt.title("Perbandingan Kalori Terbakar dengan Kadar Lemak Tubuh")

# Menambahkan label sumbu x dan y pada plot
plt.xticks(rotation = 90)
# plt.yticks([1,2,3])
plt.xlabel("Kadar Lemak Tubuh (%)")
plt.ylabel("Kalori Terbakar")


# plt.xticks(np.arange(9, 50+ 1, 1))
# ax.set_xticks(np.arange(9, 50+ 1, 1))
# plt.xticks(range(1, 238, 10), [str(i) for i in range(12, 36, 1)])

# print(plt.xticks())

# Menampilkan plot
plt.show()

"""Terdapat korelasi negatif antara kedua variabel antara Kalori Terbakar saat latihan dengan Kadar Lemak Tubuh. Semakin banyak seseorang memiliki kalori terbakar saat latihan mengindikasikan bahwa orang tersebut Kadar Lemak Tubuhnya semakin rendah.

#### 9. Perbandingan Antara Kadar Lemak Tubuh dengan Berbagai Variabel Numerik
"""

# Create a figure with six plots (2 rows, 3 columns)
plt.figure(figsize=(14, 8))
plt.suptitle("Perbandingan Antara Kadar Lemak Tubuh dengan Berbagai Variabel Numerik", y=1.01)

# First plot: Fat Percentage vs. Water Intake
plt.subplot(2, 3, 1)  # 2 rows, 3 columns, first subplot
sns.regplot(x="Fat_Percentage", y="Water_Intake (liters)", data=data)
plt.title("Fat Percentage vs. Water Intake (liters)")
plt.xlabel("Fat Percentage (%)")
plt.ylabel("Water Intake (liters)")
plt.xticks(rotation=90)
plt.xticks(np.arange(9, data["Fat_Percentage"].max() + 1, 5))

# Second plot: Fat Percentage vs. Session Duration
plt.subplot(2, 3, 2)  # 2 rows, 3 columns, second subplot
sns.regplot(x="Fat_Percentage", y="Session_Duration (hours)", data=data)
plt.title("Fat Percentage vs. Session Duration (hours)")
plt.xlabel("Fat Percentage (%)")
plt.ylabel("Session Duration (hours)")
plt.xticks(rotation=90)
plt.xticks(np.arange(9, data["Fat_Percentage"].max() + 1, 5))

# Third plot: Fat Percentage vs. Max BPM
plt.subplot(2, 3, 3)  # 2 rows, 3 columns, third subplot
sns.regplot(x="Fat_Percentage", y="Max_BPM", data=data)
plt.title("Fat Percentage vs. Max BPM")
plt.xlabel("Fat Percentage (%)")
plt.ylabel("Max BPM")
plt.xticks(rotation=90)
plt.xticks(np.arange(9, data["Fat_Percentage"].max() + 1, 5))

# Fourth plot: Fat Percentage vs. Avg BPM
plt.subplot(2, 3, 4)  # 2 rows, 3 columns, fourth subplot
sns.regplot(x="Fat_Percentage", y="Avg_BPM", data=data)
plt.title("Fat Percentage vs. Avg BPM")
plt.xlabel("Fat Percentage (%)")
plt.ylabel("Avg BPM")
plt.xticks(rotation=90)
plt.xticks(np.arange(9, data["Fat_Percentage"].max() + 1, 5))

# Fifth plot: Fat Percentage vs. Resting BPM
plt.subplot(2, 3, 5)  # 2 rows, 3 columns, fifth subplot
sns.regplot(x="Fat_Percentage", y="Resting_BPM", data=data)
plt.title("Fat Percentage vs. Resting BPM")
plt.xlabel("Fat Percentage (%)")
plt.ylabel("Resting BPM")
plt.xticks(rotation=90)
plt.xticks(np.arange(9, data["Fat_Percentage"].max() + 1, 5))

# Sixth plot: Fat Percentage vs. Age
plt.subplot(2, 3, 6)  # 2 rows, 3 columns, sixth subplot
sns.regplot(x="Fat_Percentage", y="Age", data=data)
plt.title("Fat Percentage vs. Age")
plt.xlabel("Fat Percentage (%)")
plt.ylabel("Age")
plt.xticks(rotation=90)
plt.xticks(np.arange(9, data["Fat_Percentage"].max() + 1, 5))

# Adjust layout to avoid overlap
plt.tight_layout()

# Show the plot
plt.show()

"""Grafik ini menunjukkan hubungan antara persentase lemak tubuh dengan beberapa variabel numerik lainnya. Pada hubungan antara **persentase lemak tubuh dan asupan air (Water Intake)** terlihat adanya korelasi negatif, di mana semakin tinggi persentase lemak tubuh, rata-rata asupan air cenderung menurun. Pola serupa juga terlihat pada hubungan dengan **durasi latihan (Session Duration)**, yang menunjukkan bahwa individu dengan persentase lemak tubuh lebih tinggi cenderung memiliki durasi olahraga yang lebih pendek. Namun, untuk hubungan dengan variabel seperti **denyut jantung maksimum (Max BPM)**, **denyut jantung rata-rata (Avg BPM)**, dan **denyut jantung istirahat (Resting BPM)**, tidak ditemukan korelasi yang signifikan, karena data tampak tersebar secara acak. Begitu pula untuk **usia**, grafik menunjukkan bahwa persentase lemak tubuh tidak memiliki hubungan yang jelas dengan umur. Secara keseluruhan, hubungan paling menonjol adalah antara lemak tubuh dengan asupan air dan durasi olahraga, sedangkan variabel lain tidak menunjukkan pola yang jelas.

#### 10. Perbandingan Antara Kalori Terbakar dengan Berbagai Variabel Numerik
"""

# Create a figure with six plots (2 rows, 3 columns)
plt.figure(figsize=(14, 8))
plt.suptitle("Perbandingan Antara Kalori Terbakar dengan Berbagai Variabel Numerik", y=1.01)

# First plot: Calories Burned vs. Water Intake
plt.subplot(2, 3, 1)  # 2 rows, 3 columns, first subplot
sns.regplot(x="Calories_Burned", y="Water_Intake (liters)", data=data)
plt.title("Calories Burned vs. Water Intake (liters)")
plt.xlabel("Calories Burned")
plt.ylabel("Water Intake (liters)")
plt.xticks(rotation=90)
plt.xticks(np.arange(9, data["Calories_Burned"].max() + 1, 500))

# Second plot: Calories Burned vs. Session Duration
plt.subplot(2, 3, 2)  # 2 rows, 3 columns, second subplot
sns.regplot(x="Calories_Burned", y="Session_Duration (hours)", data=data)
plt.title("Calories Burned vs. Session Duration (hours)")
plt.xlabel("Calories Burned")
plt.ylabel("Session Duration (hours)")
plt.xticks(rotation=90)
plt.xticks(np.arange(9, data["Calories_Burned"].max() + 1, 500))

# Third plot: Calories Burned vs. Max BPM
plt.subplot(2, 3, 3)  # 2 rows, 3 columns, third subplot
sns.regplot(x="Calories_Burned", y="Max_BPM", data=data)
plt.title("Calories Burned vs. Max BPM")
plt.xlabel("Calories Burned")
plt.ylabel("Max BPM")
plt.xticks(rotation=90)
plt.xticks(np.arange(9, data["Calories_Burned"].max() + 1, 500))

# Fourth plot: Calories Burned vs. Avg BPM
plt.subplot(2, 3, 4)  # 2 rows, 3 columns, fourth subplot
sns.regplot(x="Calories_Burned", y="Avg_BPM", data=data)
plt.title("Calories Burned vs. Avg BPM")
plt.xlabel("Calories Burned")
plt.ylabel("Avg BPM")
plt.xticks(rotation=90)
plt.xticks(np.arange(9, data["Calories_Burned"].max() + 1, 500))

# Fifth plot: Calories Burned vs. Resting BPM
plt.subplot(2, 3, 5)  # 2 rows, 3 columns, fifth subplot
sns.regplot(x="Calories_Burned", y="Resting_BPM", data=data)
plt.title("Calories Burned vs. Resting BPM")
plt.xlabel("Calories Burned")
plt.ylabel("Resting BPM")
plt.xticks(rotation=90)
plt.xticks(np.arange(9, data["Calories_Burned"].max() + 1, 500))

# Sixth plot: Calories Burned vs. Age
plt.subplot(2, 3, 6)  # 2 rows, 3 columns, sixth subplot
sns.regplot(x="Calories_Burned", y="Age", data=data)
plt.title("Calories Burned vs. Age")
plt.xlabel("Calories Burned")
plt.ylabel("Age")
plt.xticks(rotation=90)
plt.xticks(np.arange(9, data["Calories_Burned"].max() + 1, 500))

# Adjust layout to avoid overlap
plt.tight_layout()

# Show the plot
plt.show()

"""Grafik ini menunjukkan hubungan antara jumlah kalori yang terbakar dengan berbagai variabel numerik lainnya. Hubungan yang paling kuat terlihat pada grafik **Calories Burned vs. Session Duration**, di mana semakin lama durasi sesi olahraga, semakin banyak kalori yang terbakar, menunjukkan korelasi linear yang jelas. Pada hubungan dengan **water intake**, terdapat korelasi positif ringan, di mana asupan air cenderung meningkat seiring dengan kalori yang terbakar, meskipun data tersebar cukup luas. Korelasi positif juga terlihat pada hubungan dengan **Average BPM (denyut jantung rata-rata)**, di mana kalori yang terbakar cenderung lebih tinggi pada aktivitas dengan denyut rata-rata lebih besar. Sebaliknya, variabel seperti **Max BPM (denyut jantung maksimum)** dan **Resting BPM (denyut istirahat)** tidak menunjukkan pola hubungan yang signifikan, dengan data yang tersebar acak. Pada hubungan dengan **usia**, terdapat pola negatif lemah, di mana jumlah kalori yang terbakar sedikit menurun pada individu yang lebih tua, meskipun hubungan ini tidak terlalu signifikan. Secara keseluruhan, durasi sesi olahraga memiliki hubungan paling signifikan dengan jumlah kalori yang terbakar, sementara variabel lainnya menunjukkan hubungan yang lemah atau tidak signifikan.

# **Rekayasa Fitur**

**Intensity Score**

Rekayasa fitur untuk menemukan **Intensity Score**, sebuah metrik yang bertujuan untuk merepresentasikan tingkat intensitas aktivitas fisik. Intensity Score dihitung dengan menggabungkan beberapa variabel terkait, seperti durasi sesi olahraga, denyut jantung rata-rata (Avg BPM), denyut jantung maksimum (Max BPM), dan kalori yang terbakar, menggunakan pendekatan berbobot atau transformasi matematis tertentu. Fitur ini diharapkan mampu memberikan gambaran yang lebih holistik tentang tingkat usaha yang dilakukan seseorang selama aktivitas fisik, sehingga dapat meningkatkan akurasi analisis dan prediksi dalam model yang digunakan.
"""

# Menghitung Intensity Score
data['Intensity_Score'] = ((data['Max_BPM'] - data['Resting_BPM']) * data['Session_Duration (hours)']) / data['Avg_BPM']

# Membuat subplot untuk kedua grafik
fig, axes = plt.subplots(1, 2, figsize=(14, 6))  # Dua grafik secara horizontal

# Grafik pertama: Fat Percentage vs Intensity Score
sns.regplot(ax=axes[0], x="Fat_Percentage", y="Intensity_Score", data=data)
axes[0].set_title("Fat Percentage vs Intensity Score")
axes[0].set_xlabel("Fat Percentage (%)")
axes[0].set_ylabel("Intensity Score")
axes[0].set_xticks(np.arange(9, data["Fat_Percentage"].max() + 1, 5))

# Grafik kedua: Calories Burned vs Intensity Score
sns.regplot(ax=axes[1], x="Calories_Burned", y="Intensity_Score", data=data)
axes[1].set_title("Calories Burned vs Intensity Score")
axes[1].set_xlabel("Calories Burned")
axes[1].set_ylabel("Intensity Score")

# Mengatur tata letak
plt.tight_layout()

# Menampilkan plot
plt.show()

"""`Skor intensitas` mempunyai hubungan signifikan dengan `Kadar Lemak Tubuh` dan jumlah `Kalori Terbakar`. Semakin tinggi `skor intensitas` maka biasanya orang tersebut mempunyai kadar lemak tubuh yang lebih rendah. Sedangkan pada `kalori terbakar` semakin tinggi intensitas maka semakin tinggi pula `kalori terbakar`.

**HR Index**  

Langkah ini melakukan rekayasa fitur untuk menghasilkan `HR Index`, sebuah metrik yang dirancang untuk merepresentasikan tingkat intensitas aktivitas fisik berdasarkan variabel-variabel terkait denyut jantung. Fitur ini dihitung dengan menggabungkan `HR Index (Heart Rate Index)`, yang mencakup rasio antara denyut jantung saat aktivitas dan denyut jantung istirahat. HR Index diharapkan dapat memberikan gambaran yang lebih komprehensif mengenai tingkat usaha individu selama aktivitas fisik, sehingga dapat digunakan sebagai indikator utama dalam analisis performa atau prediksi tingkat kebugaran.
"""

# Calculate HR_Index: Max_BPM - Resting_BPM divided by Avg_BPM
data['HR_Index'] = (data['Max_BPM'] - data['Resting_BPM']) / data['Avg_BPM']

# Membuat subplot untuk kedua grafik
fig, axes = plt.subplots(1, 2, figsize=(14, 6))  # Dua grafik secara horizontal

# Grafik pertama: Fat Percentage vs Intensity Score
sns.regplot(ax=axes[0], x="Fat_Percentage", y="HR_Index", data=data)
axes[0].set_title("Fat Percentage vs HR Index")
axes[0].set_xlabel("Fat Percentage (%)")
axes[0].set_ylabel("HR Index")
axes[0].set_xticks(np.arange(9, data["Fat_Percentage"].max() + 1, 5))

# Grafik kedua: Calories Burned vs Intensity Score
sns.regplot(ax=axes[1], x="Calories_Burned", y="HR_Index", data=data)
axes[1].set_title("Calories Burned vs HR Index")
axes[1].set_xlabel("Calories Burned")
axes[1].set_ylabel("HR Index")

# Mengatur tata letak
plt.tight_layout()

# Menampilkan plot
plt.show()

"""Grafik ini menunjukkan hubungan antara `HR Index (Heart Rate Index)` dengan `Fat Percentage` dan `Calories Burned`. Hubungan antara `Fat Percentage` dan `HR Index`, terlihat bahwa tidak ada korelasi signifikan, dengan data yang tersebar acak di sekitar garis regresi yang mendatar, menunjukkan bahwa HR Index tidak dipengaruhi oleh persentase lemak tubuh. Sementara itu, hubungan antara `Calories Burned` dan `HR Index` menunjukkan korelasi negatif yang lemah, di mana `HR Index` sedikit menurun seiring meningkatnya jumlah kalori yang terbakar, meskipun hubungan ini tidak terlalu kuat karena data masih tersebar di sekitar garis regresi.

# **Persiapan Data**

Dilakukan drop pada `Workout_Frequency_cat` dan `Experiens_Level_cat` karena sudah ada dalam data sebagai numerikal. Lalu beberapa variabel kategorikal dikodifikasi dengan encoder. Setelah itu semua data numerik digunakan Standard Scaler untuk normalisasi.
"""

# Create copy of dataframe
data_processed = data.copy()

data_processed.drop('Workout_Frequency_cat', axis=1, inplace=True)
data_processed.drop('Experience_Level_cat', axis=1, inplace=True)
# Label encode categorical variables
le = LabelEncoder()
categorical_cols = ['Gender', 'Workout_Type']

for col in categorical_cols:
    if col in data_processed.columns:
        data_processed[col] = le.fit_transform(data_processed[col])

# Scale numerical features
scaler = StandardScaler()
numerical_cols = data_processed.select_dtypes(include=[np.number]).columns
data_processed[numerical_cols] = scaler.fit_transform(data_processed[numerical_cols])

"""# **Pemodelan dan Evaluasi**

Ada 4 algoritma yang dipilih dengan framework yang berbeda yaitu Random Forest, K-Nearest Neighbors, Support Vector Rgeressor dan XGboost. Random Forest (RF) unggul dalam menangani data kompleks dan besar, serta dapat mengurangi risiko overfitting dengan menggunakan banyak pohon keputusan tanpa membutuhkan praproses data yang rumit. Namun, proses pelatihan dan prediksi bisa lebih lambat dan sulit diinterpretasi. K-Nearest Neighbors (KNN) sederhana dan mudah dipahami, tidak memerlukan pelatihan, serta dapat digunakan untuk regresi dan klasifikasi, tetapi kinerjanya menurun pada dataset besar dan sangat sensitif terhadap noise serta data yang tidak seimbang. Support Vector Regression (SVR) efektif untuk data dengan dimensi tinggi dan linearitas kompleks serta dapat menangani noise, namun kurang efisien untuk dataset besar dan sulit diinterpretasi karena bergantung pada pemilihan kernel dan parameter yang tepat. XGBoost cepat, efisien, dan sering menghasilkan akurasi tinggi dengan regularisasi yang baik untuk mengurangi overfitting, namun dapat overfit jika tidak dikonfigurasi dengan benar, memerlukan pemilihan hyperparameter yang tepat, dan model yang dihasilkan sulit diinterpretasi.

Setelah itu dipilih dua metrik untuk digunakan sebagai pembanding yaitu Adjusted R² dan Mean Squared Error. Keduanya dipilih karena variabel independen digunakan tidak hanya satu jadi dibutuhkan metrik yang andal dengan jumlah variabel independen yang lebih dari satu.

* Adjusted R² (Adjusted R-Squared)

R² mengukur seberapa baik model regresi linier dapat menjelaskan variasi data. Nilainya antara 0 hingga 1, semakin tinggi nilai R², semakin baik model dalam menjelaskan data. Namun, R² bisa meningkat hanya dengan menambahkan variabel independen ke dalam model, meskipun variabel tersebut mungkin tidak relevan. Karena itu, Adjusted R² digunakan untuk memberikan penilaian yang lebih akurat.

Formula Adjusted R²:

`Adjusted R² = 1 - ((1 - R²) * (n - 1)) / (n - p - 1)`

R²: Koefisien determinasi

n: Jumlah data (observasi)

p: Jumlah variabel independen

Cara Kerja:

Adjusted R² memperhitungkan jumlah variabel dan jumlah data, membuatnya lebih andal daripada R² saat membandingkan model dengan jumlah variabel yang berbeda.
Jika variabel baru ditambahkan dan relevan, Adjusted R² akan meningkat. Sebaliknya, jika variabel tersebut tidak relevan, Adjusted R² akan menurun, menunjukkan model menjadi lebih kompleks tanpa nilai tambah.
Adjusted R² lebih cocok digunakan untuk membandingkan model yang memiliki jumlah variabel yang berbeda.
Contoh:
Jika Adjusted R² sebuah model adalah 0.85, itu berarti model tersebut dapat menjelaskan 85% variasi data dengan memperhitungkan jumlah variabel dalam model.

* MSE (Mean Squared Error)

MSE adalah ukuran yang digunakan untuk menghitung rata-rata kesalahan kuadrat antara nilai yang diprediksi oleh model dan nilai aktual. Ini adalah alat yang digunakan untuk mengevaluasi akurasi prediksi model.

Formula MSE:

`MSE = (1 / n) * Σ(yᵢ - ŷᵢ)²`

yᵢ: Nilai aktual (observasi sebenarnya)

ŷᵢ: Nilai prediksi model

n: Jumlah data (observasi)

Cara Kerja:

MSE mengukur rata-rata kuadrat selisih antara nilai yang diprediksi dan nilai yang sebenarnya.
Nilai MSE yang lebih kecil menunjukkan model yang lebih baik, karena perbedaan antara nilai yang diprediksi dan nilai aktual lebih kecil.
MSE sangat sensitif terhadap outlier, karena kesalahan dihitung dalam bentuk kuadrat. Jadi, jika ada data yang sangat berbeda, MSE bisa menjadi lebih besar.
Contoh:
Jika MSE model adalah 4, itu berarti rata-rata kuadrat perbedaan antara nilai prediksi dan nilai aktual adalah 4, menunjukkan model memiliki kesalahan yang relatif besar dibandingkan dengan model dengan MSE lebih kecil.

## Model Kalori Terbakar

Pembuatan data untuk model Kalori Terbakar yaitu dengan mendrop kolom Kalori Terbakar dari keseluruhan Data untuk membentuk nilai X sebagai variabel bebas. Semua kolom digunakan kecuali kolom Kalori Terbakar yang akan digunakan sebagai y atau variabek terikat.
"""

# Prepare features and target
X = data_processed.drop('Calories_Burned', axis=1)
y = data_processed['Calories_Burned']

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.2,
                                                    random_state=42)
X_train.head()

# DataFrame untuk menyimpan hasil evaluasi
# if 'metrics_df' not in locals() or metrics_df.empty:  # Memastikan DataFrame kosong atau belum ada

metrics_df = pd.DataFrame(columns=["Model", "R2 Score", "Adjusted R2", "RMSE", "MAE", "MSE", "Explained Variance"])
metrics_df.head()

"""### Random Forest

Model pertama yang dibuat adalah Random Forest Regressor dengan n_estimators sebesar 100 dan random_state sebesar 42.
"""

# Train model
modelRF = RandomForestRegressor(n_estimators=100, random_state=42)
modelRF.fit(X_train, y_train)

# Evaluasi RF
y_pred = modelRF.predict(X_test)
n = len(y_test)
p = X_test.shape[1]
r2 = r2_score(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
explained_var = explained_variance_score(y_test, y_pred)
r2_adj = 1 - (1 - r2) * (n - 1) / (n - p - 1)

# Tambahkan hasil ke DataFrame
new_row = pd.DataFrame({
    "Model": ["RF"],
    "R2 Score": [r2],
    "Adjusted R2": [r2_adj],
    "RMSE": [rmse],
    "MAE": [mae],
    "MSE": [mse],
    "Explained Variance": [explained_var]
})

metrics_df = pd.concat([metrics_df, new_row], ignore_index=True)

# Cetak hasil evaluasi RF
print(f"\nModel Performance (RF):")
perf_row = new_row.T
print(perf_row)

# Plot Actual vs Predicted (RF)
plt.figure(figsize=(8, 6))
plt.scatter(y_test, y_pred, color='blue', alpha=0.6)
plt.plot([min(y_test), max(y_test)], [min(y_test), max(y_test)], color='red', linestyle='--')  # 45-degree line
plt.title("Actual vs Predicted Values (RF)")
plt.xlabel("Actual Values")
plt.ylabel("Predicted Values")
plt.grid(True)
plt.show()

"""Model yang dihasilkan cukup bagus dengan Adjusted Rsquared sebesar 0.9676 dan MSE 0.0334 yang berada dibawah 0.1 nilainya.

### KNN

Model selanjutnya adalah K-Nearest Neighbors dengan jumlah n_neighbors=10.
"""

modelknn = KNeighborsRegressor(n_neighbors=10)
modelknn.fit(X_train, y_train)

# Evaluasi KNN
y_pred = modelknn.predict(X_test)
n = len(y_test)
p = X_test.shape[1]
r2 = r2_score(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
explained_var = explained_variance_score(y_test, y_pred)
r2_adj = 1 - (1 - r2) * (n - 1) / (n - p - 1)

# Tambahkan hasil ke DataFrame
new_row = pd.DataFrame({
    "Model": ["KNN"],
    "R2 Score": [r2],
    "Adjusted R2": [r2_adj],
    "RMSE": [rmse],
    "MAE": [mae],
    "MSE": [mse],
    "Explained Variance": [explained_var]
})

metrics_df = pd.concat([metrics_df, new_row], ignore_index=True)

# Cetak hasil evaluasi KNN
print(f"\nModel Performance (KNN):")
perf_row = new_row.T
print(perf_row)

# Plot Actual vs Predicted (KNN)
plt.figure(figsize=(8, 6))
plt.scatter(y_test, y_pred, color='blue', alpha=0.6)
plt.plot([min(y_test), max(y_test)], [min(y_test), max(y_test)], color='red', linestyle='--')  # 45-degree line
plt.title("Actual vs Predicted Values (KNN)")
plt.xlabel("Actual Values")
plt.ylabel("Predicted Values")
plt.grid(True)
plt.show()

"""Model ini tidak sebagus model sebelumnya namun masih cukup bagus di Adjusted Rsquared sebesar 0.8365 dan nilai MSE di atas 0.1 yaitu 0.1685 pada model ini.

### SVR

Model Support Vector Regression dengan C sebesar 100 dan epsilon sebesar 0.1 ini digunakan untuk menentukan regresi.
"""

modelSVR = SVR(kernel='rbf', C=100, epsilon=0.1)
modelSVR.fit(X_train, y_train)

# Evaluasi SVR
y_pred = modelSVR.predict(X_test)
n = len(y_test)
p = X_test.shape[1]
r2 = r2_score(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
explained_var = explained_variance_score(y_test, y_pred)
r2_adj = 1 - (1 - r2) * (n - 1) / (n - p - 1)

# Tambahkan hasil ke DataFrame
new_row = pd.DataFrame({
    "Model": ["SVR"],
    "R2 Score": [r2],
    "Adjusted R2": [r2_adj],
    "RMSE": [rmse],
    "MAE": [mae],
    "MSE": [mse],
    "Explained Variance": [explained_var]
})

metrics_df = pd.concat([metrics_df, new_row], ignore_index=True)

# Cetak hasil evaluasi SVR
print(f"\nModel Performance (SVR):")
perf_row = new_row.T
print(perf_row)

# Plot Actual vs Predicted (SVR)
plt.figure(figsize=(8, 6))
plt.scatter(y_test, y_pred, color='blue', alpha=0.6)
plt.plot([min(y_test), max(y_test)], [min(y_test), max(y_test)], color='red', linestyle='--')  # 45-degree line
plt.title("Actual vs Predicted Values (SVR)")
plt.xlabel("Actual Values")
plt.ylabel("Predicted Values")
plt.grid(True)
plt.show()

"""Hasil dari model ini sangat baik dengan Adjusted Rsquared sebesar 0.9696 dan MSE 0.0314.

### XGBoost

Model terakhir diperkenalkan Algoritma Boosting dengan metode Extreme Gradient atau XGBoost. berikut parameter model yang digunakan yaitu n_estimators sebesar 100, learning rate 0.1, max_depth sebesar 6, colsample_bytree sebesar 0.8, dan subsample 0.8 poin.
"""

# Initialize the model
xgboost = xgb.XGBRegressor(objective='reg:squarederror',  # Regression task
                         n_estimators=100,  # Number of boosting rounds
                         learning_rate=0.1,  # Step size at each iteration
                         max_depth=6,  # Maximum depth of a tree
                         colsample_bytree=0.8,  # Proportion of features used by each tree
                         subsample=0.8)  # Subsample ratio of the training set

# Fit the model on the training data
xgboost.fit(X_train, y_train)

# Evaluasi XGBoost
y_pred = xgboost.predict(X_test)  # Ganti `xgboost` dengan nama model Anda jika berbeda
n = len(y_test)
p = X_test.shape[1]
r2 = r2_score(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
explained_var = explained_variance_score(y_test, y_pred)
r2_adj = 1 - (1 - r2) * (n - 1) / (n - p - 1)

# Tambahkan hasil ke DataFrame
new_row = pd.DataFrame({
    "Model": ["XGBoost"],
    "R2 Score": [r2],
    "Adjusted R2": [r2_adj],
    "RMSE": [rmse],
    "MAE": [mae],
    "MSE": [mse],
    "Explained Variance": [explained_var]
})

metrics_df = pd.concat([metrics_df, new_row], ignore_index=True)

# Cetak hasil evaluasi XGBoost
print(f"\nModel Performance (XGBoost):")
xgboost_row = new_row.T
print(xgboost_row)

# Plot Actual vs Predicted (XGBoost)
plt.figure(figsize=(8, 6))
plt.scatter(y_test, y_pred, color='blue', alpha=0.6)
plt.plot([min(y_test), max(y_test)], [min(y_test), max(y_test)], color='red', linestyle='--')  # 45-degree line
plt.title("Actual vs Predicted Values (XGBoost)")
plt.xlabel("Actual Values")
plt.ylabel("Predicted Values")
plt.grid(True)
plt.show()

"""Hasilnya sangat bagus dengn Adjusted Rsquares sebesar 0.9854 dan MSE yang sangat kecil yaitu 0.0150 jauh dibawah model lainnya.

### Model Terbaik
"""

print(metrics_df)

# Extract the Adjusted R2 values and the corresponding model names
models = metrics_df['Model']
adjusted_r2 = metrics_df['Adjusted R2']

# Plot Adjusted R² for all models
plt.figure(figsize=(10, 6))
bars=plt.bar(models, adjusted_r2)

for bar in bars:
    yval = bar.get_height()  # Get the height of each bar (i.e., Adjusted R² value)
    plt.text(bar.get_x() + bar.get_width() / 2, yval + 0.005,  # Position text above the bar
             round(yval, 4), ha='center', va='bottom', fontsize=10)  # Format the value and position it

# Adding title and labels
plt.title('Adjusted R² for Different Models')
plt.xlabel('Model')
plt.ylabel('Adjusted R²')

# Display the plot
plt.show()

"""Model terbaik untuk variabel Kalori Terbakar adalah dengan Metode XGBoost yaitu dengan Adjusted Rsquared 0.9854.

## **Model Kadar Lemak Tubuh**

Proses pembuatan data untuk model Kadar Lemak Tubuh dilakukan dengan menghapus kolom Kadar Lemak Tubuh dari seluruh dataset, sehingga menghasilkan nilai X sebagai variabel independen. Semua kolom lainnya digunakan, kecuali kolom Kadar Lemak Tubuh yang akan menjadi variabel dependen atau y.
"""

# Prepare features and target
X = data_processed.drop(['Fat_Percentage'], axis=1)
y = data_processed['Fat_Percentage']

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.2,
                                                    random_state=42)

X.head()

# DataFrame untuk menyimpan hasil evaluasi
# if 'metrics_df' not in locals() or metrics_df.empty:  # Memastikan DataFrame kosong atau belum ada

metrics_df = pd.DataFrame(columns=["Model", "R2 Score", "Adjusted R2", "RMSE", "MAE", "MSE", "Explained Variance"])
metrics_df.head()

"""### Random Forest

Model pertama yang dibuat adalah Random Forest Regressor dengan n_estimators sebesar 100 dan random_state sebesar 42.
"""

# Train model
modelRF = RandomForestRegressor(n_estimators=100, random_state=42)
modelRF.fit(X_train, y_train)

# Evaluasi XGBoost
y_pred = modelRF.predict(X_test)
n = len(y_test)
p = X_test.shape[1]
r2 = r2_score(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
explained_var = explained_variance_score(y_test, y_pred)
r2_adj = 1 - (1 - r2) * (n - 1) / (n - p - 1)

# Tambahkan hasil ke DataFrame
new_row = pd.DataFrame({
    "Model": ["RF"],
    "R2 Score": [r2],
    "Adjusted R2": [r2_adj],
    "RMSE": [rmse],
    "MAE": [mae],
    "MSE": [mse],
    "Explained Variance": [explained_var]
})

metrics_df = pd.concat([metrics_df, new_row], ignore_index=True)

# Cetak hasil evaluasi RF
print(f"\nModel Performance (RF):")
perf_row = new_row.T
print(perf_row)

# Plot Actual vs Predicted (RF)
plt.figure(figsize=(8, 6))
plt.scatter(y_test, y_pred, color='blue', alpha=0.6)
plt.plot([min(y_test), max(y_test)], [min(y_test), max(y_test)], color='red', linestyle='--')  # 45-degree line
plt.title("Actual vs Predicted Values (RF)")
plt.xlabel("Actual Values")
plt.ylabel("Predicted Values")
plt.grid(True)
plt.show()

"""Model yang dihasilkan kurang bagus dengan Adjusted Rsquared sebesar 0.7891 dan MSE 0.1981 yang relatif besar galatnya.

### KNN

Model selanjutnya adalah K-Nearest Neighbors dengan jumlah n_neighbors=10.
"""

modelknn = KNeighborsRegressor(n_neighbors=10)
modelknn.fit(X_train, y_train)

# Evaluasi KNN
y_pred = modelknn.predict(X_test)
n = len(y_test)
p = X_test.shape[1]
r2 = r2_score(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
explained_var = explained_variance_score(y_test, y_pred)
r2_adj = 1 - (1 - r2) * (n - 1) / (n - p - 1)

# Tambahkan hasil ke DataFrame
new_row = pd.DataFrame({
    "Model": ["KNN"],
    "R2 Score": [r2],
    "Adjusted R2": [r2_adj],
    "RMSE": [rmse],
    "MAE": [mae],
    "MSE": [mse],
    "Explained Variance": [explained_var]
})

metrics_df = pd.concat([metrics_df, new_row], ignore_index=True)

# Cetak hasil evaluasi KNN
print(f"\nModel Performance (KNN):")
perf_row = new_row.T
print(perf_row)

# Plot Actual vs Predicted (KNN)
plt.figure(figsize=(8, 6))
plt.scatter(y_test, y_pred, color='blue', alpha=0.6)
plt.plot([min(y_test), max(y_test)], [min(y_test), max(y_test)], color='red', linestyle='--')  # 45-degree line
plt.title("Actual vs Predicted Values (KNN)")
plt.xlabel("Actual Values")
plt.ylabel("Predicted Values")
plt.grid(True)
plt.show()

"""Model ini lebih buruk dari model sebelumnya namun masih cukup di Adjusted Rsquared sebesar 0.7590 dan nilai MSE tinggi di atas 0.1 yaitu 0.2264 pada model ini.

### SVR

Model Support Vector Regression menggunakan teknik Gridsearch untuk menentukan parameternya. Gridsearcgh digunakan karena model awal SVR memiliki nilai metrik akurasi yang kurang bisa dipertanggung-jawabkan.
"""

# Define the parameter grid
param_grid = {
    'C': [0.1, 1, 10, 100],
    'epsilon': [0.01, 0.1, 0.5, 1],
    'gamma': ['scale', 0.1, 1, 10]
}

# Initialize SVR model
svr = SVR(kernel='rbf')

# Perform grid search
grid_search = GridSearchCV(estimator=svr, param_grid=param_grid, cv=5, scoring='neg_mean_squared_error')
grid_search.fit(X, y)

# Best parameters and score
print("Best Parameters:", grid_search.best_params_)
print("Best Score:", grid_search.best_score_)

"""Parameter model terbaik melalui Gridsearch adalah dengan C sama dengan 1, epsilon sebesar 0.5, dan gamma bernilai 'scale'."""

modelSVR = SVR(kernel='rbf', C=1, epsilon=0.5, gamma= 'scale')
modelSVR.fit(X_train, y_train)

# Evaluasi SVR
y_pred = modelSVR.predict(X_test)
n = len(y_test)
p = X_test.shape[1]
r2 = r2_score(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
explained_var = explained_variance_score(y_test, y_pred)
r2_adj = 1 - (1 - r2) * (n - 1) / (n - p - 1)

# Tambahkan hasil ke DataFrame
new_row = pd.DataFrame({
    "Model": ["SVR"],
    "R2 Score": [r2],
    "Adjusted R2": [r2_adj],
    "RMSE": [rmse],
    "MAE": [mae],
    "MSE": [mse],
    "Explained Variance": [explained_var]
})

metrics_df = pd.concat([metrics_df, new_row], ignore_index=True)

# Cetak hasil evaluasi SVR
print(f"\nModel Performance (SVR):")
perf_row = new_row.T
print(perf_row)

# Plot Actual vs Predicted (SVR)
plt.figure(figsize=(8, 6))
plt.scatter(y_test, y_pred, color='blue', alpha=0.6)
plt.plot([min(y_test), max(y_test)], [min(y_test), max(y_test)], color='red', linestyle='--')  # 45-degree line
plt.title("Actual vs Predicted Values (SVR)")
plt.xlabel("Actual Values")
plt.ylabel("Predicted Values")
plt.grid(True)
plt.show()

"""Hasil dari model ini kurang baik dengan Adjusted Rsquared sebesar 0.7469 dan MSE 0.2378.

### XGBoost

Model terakhir diperkenalkan Algoritma Boosting dengan metode Extreme Gradient atau XGBoost. Berikut parameter model yang digunakan yaitu dicari melalu Gridsearch karena hasil iterasi pertama model menghasilkan akurasi yang sangat rendah.
"""

# Define the parameter grid
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [3, 6, 10],
    'learning_rate': [0.01, 0.1, 0.2],
    'subsample': [0.8, 1.0],
    'colsample_bytree': [0.8, 1.0],
    'gamma': [0, 0.1, 0.2],
    'reg_alpha': [0, 0.1, 1.0],
    'reg_lambda': [1.0, 10.0]
}

# Initialize the XGBoost model
xgb_model = XGBRegressor(objective='reg:squarederror', random_state=42)

# Set up GridSearchCV
grid_search = GridSearchCV(
    estimator=xgb_model,
    param_grid=param_grid,
    scoring='neg_mean_squared_error',
    cv=3,
    verbose=1,
    n_jobs=-1
)

# Perform grid search
grid_search.fit(X_train, y_train)

# Get the best parameters and score
best_params = grid_search.best_params_
best_score = -grid_search.best_score_
print("Best Parameters:", best_params)
print("Best Training RMSE:", np.sqrt(best_score))

# Evaluate the best model on the test set
best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test)
test_rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print("Test RMSE:", test_rmse)

"""Parameter yang didapat adalah n_estimators sebesar 50, learning rate 0.1, max_depth sebesar 3, colsample_bytree sebesar 0.8, subsample 1.0 lalu reg_alpha 0, dan reg_lambda sebesar 10.0 poin."""

# Initialize the model
xgboost = xgb.XGBRegressor(objective='reg:squarederror',  # Regression task
                         n_estimators=50,  # Number of boosting rounds
                         learning_rate=0.1,  # Step size at each iteration
                         max_depth=3,  # Maximum depth of a tree
                         colsample_bytree=0.8,  # Proportion of features used by each tree
                         subsample=1.0,  # Subsample ratio of the training set
                         reg_alpha= 0,
                         reg_lambda= 10.0,
                         gamma= 0.2)

# Fit the model on the training data
xgboost.fit(X_train, y_train)

# Evaluasi XGBoost
y_pred = xgboost.predict(X_test)  # Ganti `xgboost` dengan nama model Anda jika berbeda
n = len(y_test)
p = X_test.shape[1]
r2 = r2_score(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
explained_var = explained_variance_score(y_test, y_pred)
r2_adj = 1 - (1 - r2) * (n - 1) / (n - p - 1)

# Tambahkan hasil ke DataFrame
new_row = pd.DataFrame({
    "Model": ["XGBoost"],
    "R2 Score": [r2],
    "Adjusted R2": [r2_adj],
    "RMSE": [rmse],
    "MAE": [mae],
    "MSE": [mse],
    "Explained Variance": [explained_var]
})

metrics_df = pd.concat([metrics_df, new_row], ignore_index=True)

# Cetak hasil evaluasi XGBoost
print(f"\nModel Performance (XGBoost):")
xgboost_row = new_row.T
print(xgboost_row)

# Plot Actual vs Predicted (XGBoost)
plt.figure(figsize=(8, 6))
plt.scatter(y_test, y_pred, color='blue', alpha=0.6)
plt.plot([min(y_test), max(y_test)], [min(y_test), max(y_test)], color='red', linestyle='--')  # 45-degree line
plt.title("Actual vs Predicted Values (XGBoost)")
plt.xlabel("Actual Values")
plt.ylabel("Predicted Values")
plt.grid(True)
plt.show()

"""Hasilnya agak sedikit lebih baik dengn Adjusted Rsquares sebesar 0.777978 dan MSE yang masih diatas 0.1 yaitu 0.2086 poin.

### Model Terbaik
"""

print(metrics_df)

# Extract the Adjusted R2 values and the corresponding model names
models = metrics_df['Model']
adjusted_r2 = metrics_df['Adjusted R2']

# Plot Adjusted R² for all models
plt.figure(figsize=(10, 6))
bars=plt.bar(models, adjusted_r2)

for bar in bars:
    yval = bar.get_height()  # Get the height of each bar (i.e., Adjusted R² value)
    plt.text(bar.get_x() + bar.get_width() / 2, yval + 0.005,  # Position text above the bar
             round(yval, 4), ha='center', va='bottom', fontsize=10)  # Format the value and position it

# Adding title and labels
plt.title('Adjusted R² for Different Models')
plt.xlabel('Model')
plt.ylabel('Adjusted R²')

# Display the plot
plt.show()

"""Model terbaik untuk variabel Kadar Lemak Tubuh ternyata adalah model Random Forest dengan Adjusted Rsquared sebesar 0.7891 terbesar dari yang lain.

# Kesimpulan

Kesimpulan berdasarkan hasil dari *goal* yang telah dicapai:  

1. **Model Prediksi Kalori Terbakar**  
   Model prediksi kalori terbakar menunjukkan kinerja yang sangat baik dengan *adjusted R²* sebesar **0.9854** dengan menggunakan algoritma XGBoost, menandakan bahwa model mampu menjelaskan sebagian besar variabilitas dalam jumlah kalori yang terbakar. Hal ini menunjukkan potensi yang tinggi untuk mengimplementasikan model ini dalam memberikan rekomendasi latihan yang efisien.


2. **Model Prediksi Kadar Lemak Tubuh**  
   Model prediksi kadar lemak tubuh memiliki *adjusted R²* sebesar **0.7891** dengan menggunakan algoritma Random Forest, menunjukkan bahwa model ini cukup baik dalam memprediksi kadar lemak tubuh. Namun, masih ada ruang untuk meningkatkan akurasi model, mungkin dengan menambahkan variabel atau data yang lebih relevan.  

3. **Preferensi Latihan Berdasarkan Gender**  
   Analisis tidak menemukan perbedaan yang signifikan dalam preferensi latihan antara laki-laki dan perempuan. Hal ini mengindikasikan bahwa program latihan dapat dirancang dengan pendekatan yang lebih universal tanpa perlu segregasi berdasarkan gender.  

4. **Preferensi Berdasarkan Tingkat Kemahiran**  
   Tidak ada hubungan signifikan yang ditemukan antara tingkat kemahiran dan preferensi latihan. Artinya, preferensi latihan kemungkinan lebih dipengaruhi oleh faktor lain, seperti tujuan kebugaran individu atau akses ke fasilitas, daripada tingkat pengalaman.  


Secara keseluruhan, model prediksi yang kuat untuk kalori terbakar dan kadar lemak tubuh telah berhasil dibuat. Hasil analisis preferensi menunjukkan bahwa pendekatan universal dapat diambil tanpa perlu memperhatikan perbedaan gender atau tingkat kemahiran. Langkah selanjutnya dapat difokuskan pada pengembangan program latihan berbasis data, peningkatan model kadar lemak tubuh, atau eksplorasi faktor-faktor lain yang mungkin memengaruhi preferensi individu.

# Akhir
"""

# !pip install nbconvert
!jupyter nbconvert --to markdown /content/gambar.ipynb

!zip -r gambar_files.zip gambar_files

"""# Referensi

- Gough, A., et al. (2018). Personalized Fitness: Trends in the Digital Fitness Industry. *Journal of Health & Wellness*.

- McAuley, E., et al. (2011). Social Support and Self-Efficacy in Exercise. *Health Psychology*.

- World Health Organization. (2020). *Physical Activity*. Retrieved from [WHO](https://www.who.int/news-room/fact-sheets/detail/physical-activity).

- Tan, J. S. A., Che Embi, Z., & Hashim, N. (2024). Comparison of Machine Learning Methods for Calories Burn Prediction. *Journal of Informatics and Web Engineering*, 3(1), 182-191. [https://doi.org/10.33093/jiwe.2024.3.1.12](https://doi.org/10.33093/jiwe.2024.3.1.12)

- Kadam, A., Shrivastava, A., Pawar, S. K., Patil, V. H., Michaelson, J., & Singh, A. (n.d.). *Calories Burned Prediction Using Machine Learning*. IEEE. Retrieved from [Calories Burn Prediction](https://hossainlab.github.io/projects/Calories_Burnt/02_Calories%20Burnt%20Prediction.html)
"""